"""Models for rule-based findings."""

from __future__ import annotations

from pydantic import BaseModel, Field


class RuleFinding(BaseModel):
    """A finding generated by a deterministic detection rule."""

    rule_id: str
    source: str = "behavioral"
    title: str
    severity: str
    description: str
    evidence: list[str] = Field(default_factory=list)
    mitre_attack: list[str] = Field(default_factory=list)
